### ISSUE TITLE
Circuitpython in HASS

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit_CircuitPython_BLE#12]
Are there any plans to support this bluetooth to mqtt gateway [bt-mqtt-gateway](https://github.com/zewelor/bt-mqtt-gateway) or any other software to use a circuitpython device in a home automated system.

I've no idea how this Bluetooth stuff works. Characteristics, Service, Descriptor puhh. 
Otherwise i would start writing a so called 'worker' for the _bt-mqtt-gateway_. 

It would be awesome to embed a circuitpython device into an existing [HASS](https://www.home-assistant.io/hassio/installation/) System.

**Comment by ladyada** [comment]
hiya please get any details for the BTLE characteristics, or ask them to provide the interface they expect

**Comment by Tasm-Devil** [comment]
OK. But are there any attempts from adafruit to provide a kind of gateway between circuitpython <-> btle <-> getaway (rpi) <-> mqtt <-> adafruitio (e.g.) ?

A kind of tunneled socket (over btle) to circuitpython would me even nicer.

**Comment by ladyada** [comment]
not yet! if you get somewhere with it let us know :)

**Comment by Tasm-Devil** [comment]
Meybe this is the way we should go: https://github.com/olliephillips/webbleMQ

**Comment by Tasm-Devil** [comment]
I have now ssl on my own mosquitto server and webbleMQ works like a charm. You can try it here:
[tasm-devils webbleMQ](https://tasm-devil.github.io/webbleMQ/)

This is the most easy way to bridge BLE UART to your mqtt server.

**Comment by Tasm-Devil** [comment]
https://github.com/adafruit/circuitpython/issues/1843
