### ISSUE TITLE
BLEConnection object can not find my defined Service 

### ISSUE THREAD

**Issue by KevinUrrutia** [adafruit/Adafruit_CircuitPython_BLE#126]
Hello, 
So I am trying to use my husarion Rosbot to connect and receive file data from the nrf52 bluefruit BLE microprocessor. So the bluefruit already has defined Services and is advertising these services. This service has already been given permission to accept read and writing from the central. So, the thing is that I can connect to the bluefruit from the linux central device just fine, and even print out the defined 128-bit UUID onto the terminal showing that the central device can see all services being advertised but when I go to access the defined service and then want to write to it I get the error:
`raise KeyError("{!r} object has no service {}".format(self, key))
      KeyError: "<adafruit_ble.BLEConnection object at <0x.....> object has no service <class '__main__.scanParametersSvc'>"`

The scanParametersSvc is the one I defined. I defined this service as a class, similar to how nordic.py defines its UARTService class. 

`from adafruit_ble.services.standard import Service
from adafruit_ble.uuid import VendorUUID
from adafruit_ble.characteristics.stream import StreamOut, StreamIn

class ScanParametersSvc(Service):
	uuid = VendorUUID("00001813-0000-1000-8000-00805f9b34fb")
	_server_tx = StreamOut(
		uuid = VendorUUID("00001813-0000-1000-8000-00805f9b34fb"),
		timeout = 1.0,
		buffer_size = 12, #can be changed later on
	)
	
	_server_rx = StreamIn(
		uuid = VendorUUID("00001813-0000-1000-8000-00805f9b34fb"),
		timeout = 1.0,
		buffer_size = 12,
	)
	
	def __init__(self, service=None):
        	super().__init__(service=service)
       		self.connectable = True
        	if not service:
            		self._rx = self._server_rx
            		self._tx = self._server_tx
        	else:
            		# If we're a client then swap the characteristics we use.
            		self._tx = self._server_rx
            		self._rx = self._server_tx

	def read(self, nbytes=None):
        	"""
        	Read characters. If ``nbytes`` is specified then read at most that many 		bytes.
        	Otherwise, read everything that arrives until the connection times out.
        	Providing the number of bytes expected is highly recommended because it 		will be faster.
        	:return: Data read
       		:rtype: bytes or None
        	"""
        	return self._rx.read(nbytes)

	def readinto(self, buf, nbytes=None):
        	"""
        	Read bytes into the ``buf``. If ``nbytes`` is specified then read at most
        	that many bytes. Otherwise, read at most ``len(buf)`` bytes.
        	:return: number of bytes read and stored into ``buf``
        	:rtype: int or None (on a non-blocking error)
        	"""
        	return self._rx.readinto(buf, nbytes)

	def readline(self):
		"""
		Read a line, ending in a newline character.
		:return: the line read
		:rtype: bytes or None	
		"""
		return self._rx.readline()

	@property
	def in_waiting(self):
		"""The number of bytes in the input buffer, available to be read."""
		return self._rx.in_waiting
	
	def reset_input_buffer(self):
		"""Discard any unread characters in the input buffer."""
		self._rx.reset_input_buffer()

	def write(self, buf):
		"""Write a buffer of bytes."""
		self._tx.write(buf)
`

I know that that the VendorUUID is correct because I printed out the advertisement of the bluefruit and found this UUID there
`Address(string="d8:7b:75:6f:a9:97") SOIL_SENSE <ProvideServicesAdvertisement complete_name=SOIL_SENSE flags=<AdvertisingFlags general_discovery le_only> Services=<BoundServiceList: 00001813-0000-1000-8000-00805f9b34fb>tx_power = 0>`

The line in main that causes this error is:
`scan_parameters_svc = soil_sense_connection[ScanParametersSvc]`

I find this error confusing because I am able to get the device information easily, and this is once again another type of Service that the bluefruit offers. So my question is why is it able to read or access one service but not another. 

I tried also to change the connection from bleak to hcitools since I am running a linux central by using 
`ble._adapter.ble_backend = 'hcitools`
and then running the python3.8 file as sudo. 

Thank you

**Comment by tannewt** [comment]
Please ask on the forums here: https://forums.adafruit.com/viewforum.php?f=60 and include the code you are running on the microcontroller too. Thanks!
