### ISSUE TITLE
macOS Big Sur troubleshooting: Abort trap: 6

### ISSUE THREAD

**Issue by cygann** [adafruit/Adafruit_CircuitPython_BLE#129]
Attempting to run a simple example on my computer (macOS Big Sur), the program would crash almost immediately with the following error message (no other information):
```
Abort trap: 6
```

After a bit of web searching, I found that I needed to add my terminal application to the Bluetooth privacy permissions under System Preferences > Security & Privacy > Privacy > Bluetooth. After doing this everything worked!

This is not an impending issue as I resolved it, but I thought it would be helpful to anyone facing a similar problem in the future.

**Comment by cygann** [comment]
As noted above, this has been resolved.

**Comment by dhalbert** [comment]
Thanks, we will add this to the appropriate Learn Guide(s).
