### ISSUE TITLE
Peripheral name length limit?

### ISSUE THREAD

**Issue by Arudinne** [adafruit/Adafruit_CircuitPython_BLE#13]
Hello,

I tried editing line 68 in uart.py to set the name as per this link:
https://circuitpython.readthedocs.io/en/latest/shared-bindings/bleio/Device.html

'''
self._periph = Peripheral((nus_uart_service,), name='1234556789')
'''

However regardless of what app I try to use to connect it looks like it's truncating the name to 5 characters. 

Example:

![Screenshot_20190601-231724_Bluefruit](https://user-images.githubusercontent.com/29390020/58756711-a009d980-84c3-11e9-8eb1-606f5e6cda02.jpg)

Is this a way around this limit?

**Comment by dhalbert** [comment]
In the original advertising packet, there's not enough room for the complete device name. The packet is only 31 bytes, and we need to include the service UUIDs, etc.

The complete name can be sent in a scan response packet: The scanner receives an advertisement, requests a scan response, and then further information is sent in the response, including the full name. But we haven't implemented scan responses yet. I'm working on this code right now and will be doing this soon. The original implementation was just enough to get minimal BLE peripheral support working to communicate, and there's a lot more to do. The API's may be changing slightly as we add more features. We'll have a beta with more functionality in the relatively near future.

**Comment by Arudinne** [comment]
OK, well I guess that answers that then. Thanks!
