### ISSUE TITLE
How to Use BatteryService with HeartRateService?

### ISSUE THREAD

**Issue by rocketsciencenerd** [adafruit/Adafruit_CircuitPython_BLE#140]
Hi All,

I want to use this [BatteryService](https://circuitpython.readthedocs.io/projects/ble/en/latest/standard_services.html?highlight=BatteryService#adafruit_ble.services.standard.BatteryService) with a [HeartRateConnection](https://github.com/adafruit/Adafruit_CircuitPython_BLE_Heart_Rate):

```
from adafruit_ble import BLERadio
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.standard import BatteryService
from adafruit_ble_heart_rate import HeartRateService

self._ble = BLERadio()
self._connection = None

print('attempting to connect...')

for adv in self._ble.start_scan(ProvideServicesAdvertisement):
    if HeartRateService in adv.services:
        self._connection = self._ble.connect(adv)
        print('connected!')
        self._ble.stop_scan()
                        
        battery_level = self._connection[BatteryService].level
        print('battery level ', battery_level)  
```
The print('battery level ', battery_level)  returns `None <adafruit_ble.BLEConnection object at 0x72658f70> object has no service <class 'adafruit_ble.services.standard.BatteryService'>`

I also looked at this [example](https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/main/examples/ble_current_time_service.py) but replace CurrentTimeService with BatteryService. 

What am I missing here? Thank you!

**Comment by tannewt** [comment]
What device are you connecting to? The connection should do service discovery when you try to get the service from it.

**Comment by rocketsciencenerd** [comment]
> What board or host are you running the code on? On Linux, if you are using adafruit-blinka-bleio, I believe the Battery Service is treated specially by the Linux BLE implementation.

Ah this is good information, it is a Linux board - Raspbian GNU/Linux10 (buster)

**Comment by rocketsciencenerd** [comment]
Update (for future developers):

When on a linux system, BlueZ interferes with bleak. Therefore, it needs to be disabled to use the `adafruit_circuitpython_ble` library to read a battery level on a BLE device. 

From this [post](https://github.com/hbldh/bleak/issues/393), you can disable the BlueZ battery plugin by editing the `bluetooth.service` file located at `/lib/systemd/system/bluetooth.service` as shown below.

```
[Service]
ExecStart=-/usr/lib/bluetooth/bluetoothd -P battery
```

Then you can request battery level this way

```
from adafruit_ble import BLERadio
from adafruit_ble.advertising.standard import ProvideServicesAdvertisement
from adafruit_ble.services.standard import BatteryService
from adafruit_ble_heart_rate import HeartRateService

class HeartRateMonitor:
    
    self._ble = BLERadio()
    self._connection = None

    def connect(self): # Connect to BLE Heart Rate Monitor
        while not self._connection:
            for adv in self._ble.start_scan(ProvideServicesAdvertisement, timeout=Polar.TIMEOUT):
                if HeartRateService in adv.services:
                   self._connection = self._ble.connect(adv)
                   self._ble.stop_scan()
                   break

    def request_battery_level(self):
        battery_level = self._connection[BatteryService].level  
        return battery_level. # This reads battery level correctly (e.g. 30 - which is 30%)

```
