### ISSUE TITLE
PyPortal start_scan(): NotImplementedError

### ISSUE THREAD

**Issue by jhfoo** [adafruit/Adafruit_CircuitPython_BLE#161]
Here's what I did on my PyPortal:
1. Referenced this doc to upgrade ESP32 firmware to 1.7.4: [https://learn.adafruit.com/adafruit-pyp ... python-ble](https://learn.adafruit.com/adafruit-pyportal/circuitpython-ble)
2. Referenced this doc for BLE scanning: [https://docs.circuitpython.org/projects ... mples.html](https://docs.circuitpython.org/projects/ble/en/latest/examples.html)
3. Upgraded CircuitPython to 7.2.5

Here's my code:
```
esp32 = ESP32()
Esp32Adapter = esp32.start_bluetooth()
ble = BLERadio(Esp32Adapter)
for advert in ble.start_scan():
  addr = advert.address
  print(addr, advert)
```

When running the code I get this error:
```
Traceback (most recent call last):
  File "code.py", line 117, in <module>
  File "adafruit_ble/__init__.py", line 250, in start_scan
NotImplementedError:
```

Can someone confirm if BLE is expected to work on PyPortal, or is there a mistake in my code?

**Comment by dhalbert** [comment]
As mentioned here: https://learn.adafruit.com/adafruit-pyportal/circuitpython-ble

> _Currently the AirLift support for CircuitPython only provides BLE peripheral support. BLE central is under development. So you cannot connect to BLE devices like Heart Rate monitors, etc., but you can act as a BLE peripheral yourself._

As a BLE peripheral, you cannot scan. You can only scan if you can act as a BLE central. You _can_ scan if you use an nRF52840 board, which can be both a central and peripheral.

**Comment by jhfoo** [comment]
Thanks for the clarification.
