### ISSUE TITLE
Wrap _bleio.Adapter functionality

### ISSUE THREAD

**Issue by bmeisels** [adafruit/Adafruit_CircuitPython_BLE#19]
As _bleio shouldn't be used directly anymore. The functionality of [_bleio.Adapter](https://circuitpython.readthedocs.io/en/4.x/shared-bindings/bleio/Adapter.html) should be wrapped.

**Comment by dhalbert** [comment]
Now wrapped by `BLERadio` (though some functionality like getting/setting name still needs to b added).
