### ISSUE TITLE
RuntimeError: No adapter available (Raspberry Pi Zero 2W running CircuitPython 9.1.0)

### ISSUE THREAD

**Issue by matiasbeaulieu** [adafruit/Adafruit_CircuitPython_BLE#199]
Hello,

I'm using one of the sample codes, and basically it does not let me initiate the BLE radio.

from adafruit_ble import BLERadio

ble = BLERadio()
print("scanning")
found = set()
scan_responses = set()
for advertisement in ble.start_scan():
    addr = advertisement.address
    if advertisement.scan_response and addr not in scan_responses:
        scan_responses.add(addr)
    elif not advertisement.scan_response and addr not in found:
        found.add(addr)
    else:
        continue
    print(addr, advertisement)
    print("\t" + repr(advertisement))
    print()

print("scan done")

But I can see in the doc that _bleio is supported on rpi zero 2w in the latest release (https://docs.circuitpython.org/en/latest/shared-bindings/_bleio/index.html ). Why is this happening? Thanks

**Comment by tannewt** [comment]
The _bleio support on the broadcom port requires an external airlift (esp32) board. This is the same as BLE on SAMD. We don't support the on board wifi/ble chip on the zero. This CP port is alpha quality anyway so bugs exist and aren't a priority to fix.
