### ISSUE TITLE
UART ECHO TEST failure

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_BLE#2]
![screen shot 2019-01-11 at 6 35 56 am](https://user-images.githubusercontent.com/15856834/51031849-d8883580-156b-11e9-8a01-4b1ecf9cf42b.png)
@dhalbert do you want these type of issues here or agianst CP?
I think I can repodce this  -- at least it did it twice when I tried to send more than 24 characters
See attached screenshot - it failed during the third line

```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5-120-g573c6d60b on 2019-01-11; Particle Argon with nRF52840
>>> 
>>> 
>>> import ble_uart_echo_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ble_uart_echo_test.py", line 10, in <module>
  File "adafruit_ble/uart.py", line 72, in write
  File "adafruit_ble/characteristic.py", line 110, in value
OSError: Failed to notify or indicate attribute value, err 1304x
>>> 
```

Reproduced a few more times -- it failed on the 24th character these times

It may be that this is just pushing the test too hard -- This is right around the limit for a BLE packet.

**Comment by dhalbert** [comment]
I added a FIFO to the UART, added some locking, and now it's `UARTServer`, so worth trying again.

**Comment by jerryneedell** [comment]
I am gettin gthis failure when I send anything to it ```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5-207-gf46ec0253 on 2019-01-22; Adafruit Feather nRF52840 Express with nRF52840
>>> 
>>> 
>>> import ble_uart_echo_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ble_uart_echo_test.py", line 14, in <module>
TypeError: can't convert bytes to int
>>> 
```

**Comment by jerryneedell** [comment]
changing the last line to just send the byte works 
```
from adafruit_ble.uart import UARTServer

uart = UARTServer()
uart.start_advertising()

# Wait for a connection
while not uart.connected:
    pass

while uart.connected:
    # Returns b'' if nothing was read.
    one_byte = uart.read(1)
    if one_byte:
        uart.write(one_byte)
```

but it  now fails as before for long messages -- now I get up to 27 bytes before it fails

```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5-207-gf46ec0253 on 2019-01-22; Adafruit Feather nRF52840 Express with nRF52840
>>> 
>>> import ble_uart_echo_test
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ble_uart_echo_test.py", line 14, in <module>
  File "adafruit_ble/uart.py", line 130, in write
OSError: Failed to notify or indicate attribute value, err 1304x
>>> 
```

**Comment by jerryneedell** [comment]
FYI - a few other notes:
It exits the program when I disconnect -- is that expected?

I am unable to connect to it via my iPhone or Android device -- 
The Android phone connects, but can't initialize its uart connection

so far only can connect from my desktop client  (Adafruit BlueFruit Connect)

**Comment by jerryneedell** [comment]
hmm  -- any ice what the uart.write fails for me -- on a feather_nrf52840_express -- what board are you using?

**Comment by jerryneedell** [comment]
which iPhone app are you using?

**Comment by jerryneedell** [comment]
the iPhone does recognize that it has UART service.

**Comment by jerryneedell** [comment]
I see that the usage example does not use "bytes"
```from adafruit_ble.uart import UARTServer

uart_server = UARTServer()
uart_server.start_advertising()

# Wait for a connection.
while not uart_server.connected:
    pass

uart_server.write('abc')
```

this works to my desktop client, but still not with my iPhone

**Comment by jerryneedell** [comment]
just a recap of results   -- this code works fine ```from adafruit_ble.uart import UARTServer

uart = UARTServer()
uart.start_advertising()

# Wait for a connection
while not uart.connected:
    pass

while uart.connected:
    # Returns b'' if nothing was read.
    one_byte = uart.read(1)
    if one_byte:
        uart.write(one_byte)
```
the use of "bytes" in the last line examples/ble_uart_echo_test.py does not work.

For me this only work with the Adafruit BueFruit LE Connect  app on my iPhone 6 (it has IOS 12.1 installed)  My iPhone 7 with (IOS 12.1.3) does not work (also IOS 12.1.2 did not work for me on the iPhone 7.

I cannot get any Andriod version of the Adafruit BLE Connect to work yet.

**Comment by jerryneedell** [comment]
@dhalbert Pulled this PR and testes with iPhone 7 IOS 12.1.3  --works fine for UART Echo and for cricket Controller demo!!! Nice work!

It still does not work with my Andriod phone -- The app connects, but the UART connection fails with the message "Uart protocol can not be initialized"
