### ISSUE TITLE
IBeacon test

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_BLE#3]
FYI -- using the Manufacturer ID 0x004C  - Apple  for the beacon test works well with the IOS Locate Beacon App

```from adafruit_ble.beacon import LocationBeacon
from adafruit_ble.uuid import UUID
test_uuid = UUID('12345678-1234-1234-1234-123456789abc')
test_company = 0x004c
b = LocationBeacon(test_company, test_uuid,123, 234, -54)
b.start()
```

**Comment by jerryneedell** [comment]
![1e76fdd7-7b62-441e-a46b-c244ab192496](https://user-images.githubusercontent.com/15856834/51086630-cbf41080-1716-11e9-9159-8991a59685b7.png)

**Comment by jerryneedell** [comment]
The Locate Beacon app also detected the EddyStone Beacon test

**Comment by dhalbert** [comment]
Thanks for the testing!!
