### ISSUE TITLE
ble_hid_periph.py does not work for me

### ISSUE THREAD

**Issue by kohlerm** [adafruit/Adafruit_CircuitPython_BLE#46]
https://github.com/adafruit/Adafruit_CircuitPython_BLE/blob/master/examples/ble_hid_periph.py
does not work for me because the Keyboard constructor does not expect an argument.
I checked the library and it does not seem to be support that argument. 
Anything I'm missing here?

**Comment by kohlerm** [comment]
Looks like the change to support the argument was reverted. Anyone knows why?

**Comment by tannewt** [comment]
Oops! I tested with a version I had changed. Here is a WIP branch: https://github.com/tannewt/Adafruit_CircuitPython_HID/tree/pass_in_devices

I'll test it after lunch and then make a PR if it all looks good. Thanks for filing an issue!

**Comment by tannewt** [comment]
PR pending here: https://github.com/adafruit/Adafruit_CircuitPython_HID/pull/43

**Comment by tannewt** [comment]
Confirmed ble_hid_periph.py works with it as well.

**Comment by kohlerm** [comment]
Great let me check that on the weekend :-)

**Comment by tannewt** [comment]
This is fixed by https://github.com/adafruit/Adafruit_CircuitPython_HID/pull/43
