### ISSUE TITLE
start_scan(): if no Advertisements are given, nothing is returned.

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_BLE#75]
This recent changed to the code in `start_scan()`:
```python
            # Double check the adv_type is requested. We may return Advertisement accidentally
            # otherwise.
            if adv_type not in advertisement_types:
                continue
```
means that if no `advertisement_types` are given, no advertisements at all will be returned by `start_scan()`, so it appears as if nothing is advertising. Previously, all received advertisements would be returned as `Advertisement` objects.

@tannewt I thought I understand your change in #72, but now I realize I didn't.

I think `advertisement_types` should be set to `(Advertisement,)` if it comes in as empty.

**Comment by tannewt** [comment]
Yup, I believe we need a default for `advertisement_types` when it is empty. The bug I fixed was that when a type is given, Advertisements were returned if a scan matched the first prefix but not the class's match().
