### ISSUE TITLE
Implement __eq__ for Advertisement

### ISSUE THREAD

**Issue by kevinjwalters** [adafruit/Adafruit_CircuitPython_BLE#85]
Implementing `__eq__` method for `Advertisement` class will allow them to be compared in a useful way. Documention on how this works when some fields are not set would be useful.

Interim workaround is `bytes(ad1) == bytes(as2)`

First mentioned in comments in #79.

**Comment by tekktrik** [comment]
Resolved by PR #150!

**Comment by tannewt** [comment]
Thank you!
